import type { Pack, PackLimits } from "@/lib/billing/types";

const freeLimits: PackLimits = {
  max_workspaces: 1,
  max_agents: 1,
  max_subaccounts: 0,
  ai_messages_per_month: 50,
  ai_messages_per_day: 10,
  max_dashboards: 1,
  max_widgets_per_dashboard: 5,
  max_integrations: 3,
  voice_enabled: false,
  custom_avatar_enabled: false,
  storage_mb: 100,
  agent_energy_default: 25_000,
  agent_energy_max: 50_000,
  support_level: "community",
};

const starterLimits: PackLimits = {
  ...freeLimits,
  max_agents: 3,
  max_subaccounts: 2,
  ai_messages_per_month: 500,
  ai_messages_per_day: 50,
  max_dashboards: 3,
  max_integrations: 5,
  voice_enabled: true,
  storage_mb: 1000,
  support_level: "email",
};

const proLimits: PackLimits = {
  ...starterLimits,
  max_agents: 10,
  max_subaccounts: 5,
  ai_messages_per_month: 2000,
  ai_messages_per_day: 200,
  max_dashboards: 10,
  max_integrations: 20,
  custom_avatar_enabled: true,
  storage_mb: 10000,
  support_level: "chat",
};

const businessLimits: PackLimits = {
  ...proLimits,
  max_workspaces: -1,
  max_agents: -1,
  max_subaccounts: 20,
  ai_messages_per_month: -1,
  ai_messages_per_day: -1,
  max_dashboards: -1,
  max_integrations: -1,
  storage_mb: 100000,
  support_level: "dedicated",
};

export const LANDING_FALLBACK_PACKS: Pack[] = [
  {
    id: "fallback-free",
    name: "Free",
    slug: "free",
    description: "Get started with Monzi",
    price_monthly: 0,
    price_yearly: 0,
    stripe_price_id_monthly: null,
    stripe_price_id_yearly: null,
    is_active: true,
    is_public: true,
    sort_order: 0,
    limits: freeLimits,
  },
  {
    id: "fallback-starter",
    name: "Starter",
    slug: "starter",
    description: "For individuals getting productive",
    price_monthly: 19,
    price_yearly: 190,
    stripe_price_id_monthly: null,
    stripe_price_id_yearly: null,
    is_active: true,
    is_public: true,
    sort_order: 1,
    limits: starterLimits,
  },
  {
    id: "fallback-pro",
    name: "Pro",
    slug: "pro",
    description: "Power users and growing teams",
    price_monthly: 49,
    price_yearly: 490,
    stripe_price_id_monthly: null,
    stripe_price_id_yearly: null,
    is_active: true,
    is_public: true,
    sort_order: 2,
    limits: proLimits,
  },
  {
    id: "fallback-business",
    name: "Business",
    slug: "business",
    description: "Unlimited scale for your organization",
    price_monthly: 99,
    price_yearly: 990,
    stripe_price_id_monthly: null,
    stripe_price_id_yearly: null,
    is_active: true,
    is_public: true,
    sort_order: 3,
    limits: businessLimits,
  },
];
